=== DbCrWk/graph-norm/schema/scaffold/1.0.0.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/scaffold/1.0.0.json",
    "version": "1.0.0",
    "title": "Grano Scaffold",
    "description": "A grano scaffold file to describe a graph sequence",
    "type": "object",
    "properties": {
        "label": {
            "description": "An identifiable text identifier for this scaffold",
            "type": "string"
        },
        "version": {
            "description": "The version that the basic scaffold should be checked against",
            "type": "string",
            "enum": [
                "1.0.0"
            ]
        },
        "vertices": {
            "description": "A set of vertices to add to all entries of the graph sequence",
            "type": "array",
            "items": {
                "$ref": "#/definitions/vertex"
            },
            "minItems": 0,
            "uniqueItems": true
        },
        "edges": {
            "description": "A set of edges to add to all entries of the graph sequence",
            "type": "array",
            "items": {
                "$ref": "#/definitions/edge"
            },
            "minItems": 0,
            "uniqueItems": true
        },
        "graphs": {
            "description": "A set of graphs that can be easily referenced",
            "type": "object",
            "patternProperties": {
                "^[A-Za-z-][A-Za-z0-9_-]*$": {
                    "$ref": "#/definitions/graph"
                }
            },
            "uniqueItems": true
        },
        "sequence": {
            "description": "The graph sequence",
            "type": "array",
            "items": {
                "oneOf": [
                    {
                        "$ref": "#/definitions/graph_with_label"
                    },
                    {
                        "$ref": "#/definitions/graph_label"
                    }
                ]
            },
            "uniqueItems": false
        }
    },
    "definitions": {
        "vertex": {
            "description": "A single vertex",
            "type": [
                "number",
                "string"
            ]
        },
        "edge": {
            "description": "A single edge",
            "type": "array",
            "items": [
                {
                    "$ref": "#/definitions/vertex"
                },
                {
                    "$ref": "#/definitions/vertex"
                }
            ],
            "minItems": 2,
            "maxItems": 2,
            "additionalItems": false
        },
        "graph_label": {
            "description": "A string identifier for a graph",
            "type": "string"
        },
        "graph": {
            "type": "object",
            "properties": {
                "label": {
                    "$ref": "#/definitions/graph_label"
                },
                "edges": {
                    "description": "A set of edges for a particular graph",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/edge"
                    },
                    "minItems": 0,
                    "uniqueItems": true
                },
                "vertices": {
                    "description": "A set of vertices for this graph",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vertex"
                    },
                    "minItems": 0,
                    "uniqueItems": true
                }
            }
        },
        "graph_with_label": {
            "$ref": "#/definitions/graph",
            "required": ["label"]
        }
    },
    "required": [
        "label",
        "version",
        "sequence"
    ]
}

=== DbCrWk/graph-norm/example/waveyield.scaffold.json
{
    "label": "wave_yield",
    "$schema": "https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/scaffold/1.0.0.json",
    "version": "1.0.0",
    "vertices": [
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h"
    ],
    "edges": [],
    "graphs": {
        "g1": {
            "label": "g1",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "a",
                    "b"
                ],
                [
                    "b",
                    "c"
                ],
                [
                    "c",
                    "d"
                ],
                [
                    "d",
                    "a"
                ],
                [
                    "e",
                    "f"
                ],
                [
                    "f",
                    "g"
                ],
                [
                    "g",
                    "h"
                ],
                [
                    "h",
                    "e"
                ]
            ]
        },
        "g2": {
            "label": "g2",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "e",
                    "h"
                ],
                [
                    "h",
                    "g"
                ],
                [
                    "g",
                    "f"
                ],
                [
                    "f",
                    "e"
                ],
                [
                    "a",
                    "d"
                ],
                [
                    "d",
                    "c"
                ],
                [
                    "c",
                    "b"
                ],
                [
                    "b",
                    "a"
                ]
            ]
        },
        "g3": {
            "label": "g3",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "a",
                    "b"
                ],
                [
                    "b",
                    "c"
                ],
                [
                    "c",
                    "d"
                ],
                [
                    "d",
                    "a"
                ],
                [
                    "e",
                    "f"
                ],
                [
                    "f",
                    "g"
                ],
                [
                    "g",
                    "h"
                ],
                [
                    "h",
                    "e"
                ]
            ]
        },
        "g4": {
            "label": "g4",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "e",
                    "h"
                ],
                [
                    "h",
                    "g"
                ],
                [
                    "g",
                    "f"
                ],
                [
                    "f",
                    "e"
                ],
                [
                    "a",
                    "d"
                ],
                [
                    "d",
                    "c"
                ],
                [
                    "c",
                    "b"
                ],
                [
                    "b",
                    "a"
                ]
            ]
        },
        "g5": {
            "label": "g5",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "a",
                    "b"
                ],
                [
                    "b",
                    "c"
                ],
                [
                    "c",
                    "d"
                ],
                [
                    "d",
                    "a"
                ],
                [
                    "e",
                    "f"
                ],
                [
                    "f",
                    "g"
                ],
                [
                    "g",
                    "h"
                ],
                [
                    "h",
                    "e"
                ]
            ]
        },
        "g6": {
            "label": "g6",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "e",
                    "h"
                ],
                [
                    "h",
                    "g"
                ],
                [
                    "g",
                    "f"
                ],
                [
                    "f",
                    "e"
                ],
                [
                    "a",
                    "d"
                ],
                [
                    "d",
                    "c"
                ],
                [
                    "c",
                    "b"
                ],
                [
                    "b",
                    "a"
                ]
            ]
        },
        "g7": {
            "label": "g7",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "a",
                    "b"
                ],
                [
                    "b",
                    "c"
                ],
                [
                    "c",
                    "d"
                ],
                [
                    "d",
                    "a"
                ],
                [
                    "e",
                    "f"
                ],
                [
                    "f",
                    "g"
                ],
                [
                    "g",
                    "h"
                ],
                [
                    "h",
                    "e"
                ]
            ]
        },
        "g8": {
            "label": "g8",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "e",
                    "h"
                ],
                [
                    "h",
                    "g"
                ],
                [
                    "g",
                    "f"
                ],
                [
                    "f",
                    "e"
                ],
                [
                    "a",
                    "d"
                ],
                [
                    "d",
                    "c"
                ],
                [
                    "c",
                    "b"
                ],
                [
                    "b",
                    "a"
                ]
            ]
        }
    },
    "sequence": [
        "g1",
        "g2",
        "g3",
        "g4",
        "g5",
        "g6",
        "g7",
        "g8"
    ]
}

=== DbCrWk/graph-norm/example/t-vary.scaffold.json
{
    "label": "round",
    "$schema": "https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/scaffold/1.0.0.json",
    "version": "1.0.0",
    "vertices": [
        "a",
        "b",
        "c",
        "d",
        "e",
        "f"
    ],
    "edges": [],
    "graphs": {
        "g1": {
            "label": "g1",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f"
            ],
            "edges": [
                ["a","b"],
                ["b","a"],
                ["c", "a"],
                ["b", "c"],
                ["c", "d"],
                ["d", "c"],
                ["e", "d"],
                ["d", "f"],
                ["e", "f"],
                ["f", "e"]
            ]
        },
        "g2": {
            "label": "g2",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f"
            ],
            "edges": [
                [
                    "a",
                    "b"
                ],
                [
                    "b",
                    "a"
                ],
                [
                    "c",
                    "a"
                ],
                [
                    "b",
                    "c"
                ],
                [
                    "c",
                    "d"
                ],
                [
                    "d",
                    "c"
                ],
                [
                    "e",
                    "d"
                ],
                [
                    "e",
                    "f"
                ],
                [
                    "f",
                    "e"
                ]
            ]
        },
        "g3": {
            "label": "g3",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f"
            ],
            "edges": [
                [
                    "a",
                    "b"
                ],
                [
                    "b",
                    "a"
                ],
                [
                    "c",
                    "a"
                ],
                [
                    "c",
                    "d"
                ],
                [
                    "d",
                    "c"
                ],
                [
                    "e",
                    "f"
                ],
                [
                    "f",
                    "e"
                ]
            ]
        },
        "g4": {
            "label": "g4",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f"
            ],
            "edges": [
                [
                    "a",
                    "b"
                ],
                [
                    "b",
                    "a"
                ],
                [
                    "c",
                    "d"
                ],
                [
                    "d",
                    "c"
                ],
                [
                    "e",
                    "f"
                ],
                [
                    "f",
                    "e"
                ]
            ]
        },
        "g5": {
            "label": "g5",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f"
            ],
            "edges": [
                [
                    "a",
                    "b"
                ],
                [
                    "b",
                    "a"
                ],
                [
                    "c",
                    "d"
                ],
                [
                    "d",
                    "c"
                ]
            ]
        },
        "g6": {
            "label": "g6",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f"
            ],
            "edges": [
                [
                    "a",
                    "b"
                ],
                [
                    "b",
                    "a"
                ]
            ]
        },
        "g7": {
            "label": "g7",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f"
            ],
            "edges": []
        }
    },
    "sequence": [
        "g1",
        "g2",
        "g3",
        "g4",
        "g5",
        "g6",
        "g7"
    ]
}

=== DbCrWk/graph-norm/example/stopsign.scaffold.json
{
    "label": "round",
    "$schema": "https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/scaffold/1.0.0.json",
    "version": "1.0.0",
    "vertices": [
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h"
    ],
    "edges": [],
    "graphs": {
        "g1": {
            "label": "g1",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "a",
                    "b"
                ],
                [
                    "b",
                    "c"
                ],
                [
                    "c",
                    "d"
                ],
                [
                    "d",
                    "e"
                ],
                [
                    "e",
                    "f"
                ],
                [
                    "f",
                    "g"
                ],
                [
                    "g",
                    "h"
                ],
                [
                    "h",
                    "a"
                ]
            ]
        },
        "g2": {
            "label": "g2",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "a",
                    "h"
                ],
                [
                    "h",
                    "g"
                ],
                [
                    "g",
                    "f"
                ],
                [
                    "f",
                    "e"
                ],
                [
                    "e",
                    "d"
                ],
                [
                    "d",
                    "c"
                ],
                [
                    "c",
                    "b"
                ],
                [
                    "b",
                    "a"
                ]
            ]
        },
        "g3": {
            "label": "g3",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "a",
                    "b"
                ],
                [
                    "b",
                    "c"
                ],
                [
                    "c",
                    "d"
                ],
                [
                    "d",
                    "e"
                ],
                [
                    "e",
                    "f"
                ],
                [
                    "f",
                    "g"
                ],
                [
                    "g",
                    "h"
                ],
                [
                    "h",
                    "a"
                ]
            ]
        },
        "g4": {
            "label": "g4",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "a",
                    "h"
                ],
                [
                    "h",
                    "g"
                ],
                [
                    "g",
                    "f"
                ],
                [
                    "f",
                    "e"
                ],
                [
                    "e",
                    "d"
                ],
                [
                    "d",
                    "c"
                ],
                [
                    "c",
                    "b"
                ],
                [
                    "b",
                    "a"
                ]
            ]
        },
        "g5": {
            "label": "g5",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "a",
                    "b"
                ],
                [
                    "b",
                    "c"
                ],
                [
                    "c",
                    "d"
                ],
                [
                    "d",
                    "e"
                ],
                [
                    "e",
                    "f"
                ],
                [
                    "f",
                    "g"
                ],
                [
                    "g",
                    "h"
                ],
                [
                    "h",
                    "a"
                ]
            ]
        },
        "g6": {
            "label": "g6",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "a",
                    "h"
                ],
                [
                    "h",
                    "g"
                ],
                [
                    "g",
                    "f"
                ],
                [
                    "f",
                    "e"
                ],
                [
                    "e",
                    "d"
                ],
                [
                    "d",
                    "c"
                ],
                [
                    "c",
                    "b"
                ],
                [
                    "b",
                    "a"
                ]
            ]
        },
        "g7": {
            "label": "g7",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "a",
                    "b"
                ],
                [
                    "b",
                    "c"
                ],
                [
                    "c",
                    "d"
                ],
                [
                    "d",
                    "e"
                ],
                [
                    "e",
                    "f"
                ],
                [
                    "f",
                    "g"
                ],
                [
                    "g",
                    "h"
                ],
                [
                    "h",
                    "a"
                ]
            ]
        },
        "g8": {
            "label": "g8",
            "vertices": [
                "a",
                "b",
                "c",
                "d",
                "e",
                "f",
                "g",
                "h"
            ],
            "edges": [
                [
                    "a",
                    "h"
                ],
                [
                    "h",
                    "g"
                ],
                [
                    "g",
                    "f"
                ],
                [
                    "f",
                    "e"
                ],
                [
                    "e",
                    "d"
                ],
                [
                    "d",
                    "c"
                ],
                [
                    "c",
                    "b"
                ],
                [
                    "b",
                    "a"
                ]
            ]
        }
    },
    "sequence": [
        "g1",
        "g2",
        "g3",
        "g4",
        "g5",
        "g6",
        "g7",
        "g8"
    ]
}

=== DbCrWk/graph-norm/scaffold.json
{"$schema":"https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/scaffold/1.0.0.json","label":"autogenerated","version":"1.0.0","vertices":["1","2","3","4","5","6","7","8","9","10"],"edges":[],"graphs":{"g₁":{"label":"g₁","edges":[["2","1"],["3","2"],["3","7"],["4","4"],["4","10"],["6","3"],["6","5"],["6","10"],["7","2"],["8","1"],["9","10"]]},"g₂":{"label":"g₂","edges":[["1","6"],["1","10"],["4","2"],["5","3"],["5","4"],["6","10"],["7","3"],["7","6"],["8","3"],["9","5"]]},"g₃":{"label":"g₃","edges":[["3","2"],["3","4"],["3","7"],["5","7"],["6","8"],["8","8"]]},"g₄":{"label":"g₄","edges":[["2","3"],["2","5"],["3","3"],["3","5"],["4","3"],["4","8"],["5","8"],["6","4"],["7","3"],["7","8"],["8","1"],["8","6"],["9","9"]]},"g₅":{"label":"g₅","edges":[["1","2"],["2","4"],["4","7"],["6","8"],["7","4"],["8","4"],["9","6"],["10","7"]]},"g₆":{"label":"g₆","edges":[["1","4"],["3","9"],["3","10"],["4","5"],["5","5"],["6","9"],["8","6"]]},"g₇":{"label":"g₇","edges":[["1","1"],["1","9"],["3","8"],["4","1"],["5","7"],["5","10"],["6","7"],["6","10"],["7","1"],["7","6"],["9","3"]]},"g₈":{"label":"g₈","edges":[["1","1"],["1","3"],["2","5"],["5","2"],["6","1"],["6","10"],["7","3"],["7","8"],["8","1"],["9","10"]]},"g₉":{"label":"g₉","edges":[["1","5"],["2","1"],["2","8"],["3","6"],["4","5"],["5","1"],["5","6"],["7","8"],["8","8"]]},"g₁₀":{"label":"g₁₀","edges":[["1","4"],["3","6"],["5","1"],["8","4"],["8","5"],["9","1"],["9","3"],["9","4"]]}},"sequence":["g₁","g₂","g₃","g₄","g₅","g₆","g₇","g₈","g₉","g₁₀"]}

=== DbCrWk/graph-norm/example/round.scaffold.json
{
    "label": "round",
    "$schema": "https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/scaffold/1.0.0.json",
    "version": "1.0.0",
    "vertices": [
        "a",
        "b",
        "c"
    ],
    "edges": [],
    "graphs": {
        "g1": {
            "label": "g1",
            "vertices": ["a", "b", "c"],
            "edges": [["a", "b"]]
        },
        "g2": {
            "label": "g2",
            "vertices": ["a", "b", "c"],
            "edges": [["b", "c"]]
        },
        "g3": {
            "label": "g3",
            "vertices": ["a", "b", "c"],
            "edges": [["c", "a"]]
        }
    },
    "sequence": [
        "g1",
        "g2",
        "g3",
        "g1"
    ]
}

=== DbCrWk/graph-norm/example/basic.scaffold.json
{
    "label": "some-string",
    "$schema": "../schema/scaffold/1.0.0.json",
    "version": "1.0.0",
    "vertices": [],
    "edges": [],
    "graphs": {},
    "sequence": [
        {
            "label": "g1",
            "edges": [
                [
                    "a",
                    "b"
                ]
            ]
        }
    ]
}
