=== DbCrWk/graph-norm/schema/parse.tree/1.1.0.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/parse.tree/1.1.0.json",
    "version": "1.1.0",
    "title": "Grano Parse Tree",
    "description": "A grano file to describe a parse tree",
    "type": "object",
    "properties": {
        "label": {
            "description": "An identifiable text identifier for this tree",
            "type": "string"
        },
        "version": {
            "description": "The version that the parse.tree should be checked against",
            "type": "string",
            "enum": [
                "1.1.0"
            ]
        },
        "vertices": {
            "description": "A set of vertices to add to all entries of the graph sequence",
            "type": "array",
            "items": {
                "$ref": "#/definitions/vertex"
            },
            "minItems": 0,
            "uniqueItems": true
        },
        "graphs": {
            "description": "A set of graphs that can be easily referenced",
            "type": "object",
            "patternProperties": {
                "^[A-Za-z-][A-Za-z0-9_-]*$": {
                    "$ref": "#/definitions/graph"
                }
            },
            "uniqueItems": true
        },
        "sequence": {
            "description": "The graph sequence",
            "type": "array",
            "items": {
                "oneOf": [
                    {
                        "$ref": "#/definitions/graph_with_label"
                    },
                    {
                        "$ref": "#/definitions/graph_label"
                    }
                ]
            },
            "uniqueItems": false
        },
        "temporal": {
            "$ref": "https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/temporal.tree/1.0.0.json"
        },
        "topological": {
            "$ref": "https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/topological.tree/1.0.0.json"
        },
        "$schema": {
            "type": "string",
            "enum": [
                "https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/parse.tree/1.1.0.json"
            ]
        }
    },
    "definitions": {
        "vertex": {
            "description": "A single vertex",
            "type": [
                "number",
                "string"
            ]
        },
        "edge": {
            "description": "A single edge",
            "type": "array",
            "items": [
                {
                    "$ref": "#/definitions/vertex"
                },
                {
                    "$ref": "#/definitions/vertex"
                }
            ],
            "minItems": 2,
            "maxItems": 2,
            "additionalItems": false
        },
        "graph_label": {
            "description": "A string identifier for a graph",
            "type": "string"
        },
        "graph": {
            "type": "object",
            "properties": {
                "label": {
                    "$ref": "#/definitions/graph_label"
                },
                "edges": {
                    "description": "A set of edges for a particular graph",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/edge"
                    },
                    "minItems": 0,
                    "uniqueItems": true
                },
                "vertices": {
                    "description": "A set of vertices for this graph",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vertex"
                    },
                    "minItems": 0,
                    "uniqueItems": true
                }
            }
        },
        "graph_with_label": {
            "$ref": "#/definitions/graph",
            "required": [
                "label"
            ]
        }
    },
    "required": [
        "label",
        "version",
        "temporal",
        "topological",
        "vertices",
        "graphs",
        "sequence"
    ],
    "additionalProperties": false
}

=== DbCrWk/graph-norm/example/usa-simple.parse.tree.json
{"label":"Autogenerated Parse Tree (g1 ... g3)","$schema":"https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/parse.tree/1.1.0.json","version":"1.1.0","vertices":["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s"],"graphs":{"(g1 ... g3)":{"edges":[["a","a"],["a","b"],["a","c"],["a","d"],["a","r"],["a","g"],["a","j"],["a","e"],["a","q"],["a","s"],["a","h"],["a","i"],["a","k"],["b","b"],["b","a"],["b","c"],["b","d"],["b","r"],["b","g"],["b","j"],["b","e"],["b","q"],["b","s"],["b","h"],["b","i"],["b","k"],["b","f"],["b","p"],["c","c"],["c","a"],["c","b"],["c","d"],["c","g"],["c","j"],["c","r"],["c","e"],["c","h"],["c","i"],["c","k"],["c","q"],["c","s"],["c","f"],["c","n"],["d","d"],["d","b"],["d","c"],["d","e"],["d","a"],["d","r"],["d","g"],["d","j"],["d","f"],["d","q"],["d","s"],["d","h"],["d","i"],["d","k"],["d","p"],["r","r"],["r","b"],["r","q"],["r","s"],["r","a"],["r","c"],["r","d"],["r","p"],["r","g"],["r","j"],["r","e"],["r","f"],["g","g"],["g","c"],["g","h"],["g","i"],["g","j"],["g","a"],["g","b"],["g","d"],["g","k"],["g","r"],["g","e"],["g","n"],["j","j"],["j","c"],["j","g"],["j","k"],["j","a"],["j","b"],["j","d"],["j","h"],["j","i"],["j","n"],["j","r"],["j","e"],["j","l"],["j","m"],["j","o"],["e","e"],["e","d"],["e","f"],["e","b"],["e","c"],["e","p"],["e","a"],["e","r"],["e","g"],["e","j"],["e","q"],["q","q"],["q","p"],["q","r"],["q","f"],["q","b"],["q","s"],["q","e"],["q","a"],["q","c"],["q","d"],["s","s"],["s","r"],["s","b"],["s","q"],["s","a"],["s","c"],["s","d"],["s","p"],["h","h"],["h","g"],["h","i"],["h","c"],["h","j"],["h","a"],["h","b"],["h","d"],["h","k"],["i","i"],["i","g"],["i","h"],["i","c"],["i","j"],["i","a"],["i","b"],["i","d"],["i","k"],["k","k"],["k","j"],["k","n"],["k","c"],["k","g"],["k","l"],["k","m"],["k","o"],["k","a"],["k","b"],["k","d"],["k","h"],["k","i"],["f","f"],["f","e"],["f","p"],["f","d"],["f","q"],["f","b"],["f","c"],["f","r"],["p","p"],["p","f"],["p","q"],["p","e"],["p","r"],["p","d"],["p","b"],["p","s"],["n","n"],["n","k"],["n","l"],["n","m"],["n","o"],["n","j"],["n","c"],["n","g"],["l","l"],["l","m"],["l","n"],["l","k"],["l","o"],["l","j"],["m","m"],["m","l"],["m","n"],["m","k"],["m","o"],["m","j"],["o","o"],["o","n"],["o","k"],["o","l"],["o","m"],["o","j"]]},"(g1 ... g2)":{"edges":[["a","a"],["a","b"],["a","c"],["a","d"],["a","r"],["a","g"],["a","j"],["b","b"],["b","a"],["b","c"],["b","d"],["b","r"],["b","g"],["b","j"],["b","e"],["b","q"],["b","s"],["c","c"],["c","a"],["c","b"],["c","d"],["c","g"],["c","j"],["c","r"],["c","e"],["c","h"],["c","i"],["c","k"],["d","d"],["d","b"],["d","c"],["d","e"],["d","a"],["d","r"],["d","g"],["d","j"],["d","f"],["r","r"],["r","b"],["r","q"],["r","s"],["r","a"],["r","c"],["r","d"],["r","p"],["g","g"],["g","c"],["g","h"],["g","i"],["g","j"],["g","a"],["g","b"],["g","d"],["g","k"],["j","j"],["j","c"],["j","g"],["j","k"],["j","a"],["j","b"],["j","d"],["j","h"],["j","i"],["j","n"],["e","e"],["e","d"],["e","f"],["e","b"],["e","c"],["e","p"],["q","q"],["q","p"],["q","r"],["q","f"],["q","b"],["q","s"],["s","s"],["s","r"],["s","b"],["s","q"],["h","h"],["h","g"],["h","i"],["h","c"],["h","j"],["i","i"],["i","g"],["i","h"],["i","c"],["i","j"],["k","k"],["k","j"],["k","n"],["k","c"],["k","g"],["k","l"],["k","m"],["k","o"],["f","f"],["f","e"],["f","p"],["f","d"],["f","q"],["p","p"],["p","f"],["p","q"],["p","e"],["p","r"],["n","n"],["n","k"],["n","l"],["n","m"],["n","o"],["n","j"],["l","l"],["l","m"],["l","n"],["l","k"],["l","o"],["m","m"],["m","l"],["m","n"],["m","k"],["m","o"],["o","o"],["o","n"],["o","k"],["o","l"],["o","m"]]},"(g1 ... g1)":{"edges":[["a","a"],["a","b"],["a","c"],["b","b"],["b","a"],["b","c"],["b","d"],["b","r"],["c","c"],["c","a"],["c","b"],["c","d"],["c","g"],["c","j"],["d","d"],["d","b"],["d","c"],["d","e"],["e","e"],["e","d"],["e","f"],["f","f"],["f","e"],["f","p"],["g","g"],["g","c"],["g","h"],["g","i"],["g","j"],["h","h"],["h","g"],["h","i"],["i","i"],["i","g"],["i","h"],["j","j"],["j","c"],["j","g"],["j","k"],["k","k"],["k","j"],["k","n"],["l","l"],["l","m"],["l","n"],["m","m"],["m","l"],["m","n"],["n","n"],["n","k"],["n","l"],["n","m"],["n","o"],["o","o"],["o","n"],["p","p"],["p","f"],["p","q"],["q","q"],["q","p"],["q","r"],["r","r"],["r","b"],["r","q"],["r","s"],["s","s"],["s","r"]]},"g1":{"edges":[["a","a"],["a","b"],["a","c"],["b","b"],["b","a"],["b","c"],["b","d"],["b","r"],["c","c"],["c","a"],["c","b"],["c","d"],["c","g"],["c","j"],["d","d"],["d","b"],["d","c"],["d","e"],["e","e"],["e","d"],["e","f"],["f","f"],["f","e"],["f","p"],["g","g"],["g","c"],["g","h"],["g","i"],["g","j"],["h","h"],["h","g"],["h","i"],["i","i"],["i","g"],["i","h"],["j","j"],["j","c"],["j","g"],["j","k"],["k","k"],["k","j"],["k","n"],["l","l"],["l","m"],["l","n"],["m","m"],["m","l"],["m","n"],["n","n"],["n","k"],["n","l"],["n","m"],["n","o"],["o","o"],["o","n"],["p","p"],["p","f"],["p","q"],["q","q"],["q","p"],["q","r"],["r","r"],["r","b"],["r","q"],["r","s"],["s","s"],["s","r"]]},"g2":{"edges":[["a","a"],["a","b"],["a","c"],["b","b"],["b","a"],["b","c"],["b","d"],["b","r"],["c","c"],["c","a"],["c","b"],["c","d"],["c","g"],["c","j"],["d","d"],["d","b"],["d","c"],["d","e"],["e","e"],["e","d"],["e","f"],["f","f"],["f","e"],["f","p"],["g","g"],["g","c"],["g","h"],["g","i"],["g","j"],["h","h"],["h","g"],["h","i"],["i","i"],["i","g"],["i","h"],["j","j"],["j","c"],["j","g"],["j","k"],["k","k"],["k","j"],["k","n"],["l","l"],["l","m"],["l","n"],["m","m"],["m","l"],["m","n"],["n","n"],["n","k"],["n","l"],["n","m"],["n","o"],["o","o"],["o","n"],["p","p"],["p","f"],["p","q"],["q","q"],["q","p"],["q","r"],["r","r"],["r","b"],["r","q"],["r","s"],["s","s"],["s","r"]]},"g3":{"edges":[["a","a"],["a","b"],["a","c"],["b","b"],["b","a"],["b","c"],["b","d"],["b","r"],["c","c"],["c","a"],["c","b"],["c","d"],["c","g"],["c","j"],["d","d"],["d","b"],["d","c"],["d","e"],["e","e"],["e","d"],["e","f"],["f","f"],["f","e"],["f","p"],["g","g"],["g","c"],["g","h"],["g","i"],["g","j"],["h","h"],["h","g"],["h","i"],["i","i"],["i","g"],["i","h"],["j","j"],["j","c"],["j","g"],["j","k"],["k","k"],["k","j"],["k","n"],["l","l"],["l","m"],["l","n"],["m","m"],["m","l"],["m","n"],["n","n"],["n","k"],["n","l"],["n","m"],["n","o"],["o","o"],["o","n"],["p","p"],["p","f"],["p","q"],["q","q"],["q","p"],["q","r"],["r","r"],["r","b"],["r","q"],["r","s"],["s","s"],["s","r"]]}},"sequence":["g1","g2","g3"],"temporal":{"label":"Autogenerated ((g1 ... g3))","version":"1.0.0","root":{"category":"sequence","label":"(g1 ... g3)","isTransitive":false,"children":[{"category":"sequence","label":"(g1 ... g2)","isTransitive":false,"children":[{"category":"sequence","label":"(g1 ... g1)","isTransitive":false,"children":[{"category":"graph","label":"g1","isTransitive":false}]},{"category":"graph","label":"g2","isTransitive":false}]},{"category":"graph","label":"g3","isTransitive":false}]}},"topological":{"label":"Autogenerated (root)","version":"1.0.0","root":{"category":"root","label":"root","children":[{"category":"sequence","label":"(g1 ... g3): o","clique":"o","children":[{"category":"sequence","label":"(g1 ... g2): o","clique":"o","children":[{"category":"sequence","label":"(g1 ... g1): o","clique":"o","children":[]},{"category":"sequence","label":"(g1 ... g1): s","clique":"s","children":[]},{"category":"sequence","label":"(g1 ... g1): i","clique":"i","children":[]},{"category":"sequence","label":"(g1 ... g1): n","clique":"n","children":[]}]},{"category":"sequence","label":"(g1 ... g2): p","clique":"p","children":[{"category":"sequence","label":"(g1 ... g1): s","clique":"s","children":[]}]},{"category":"sequence","label":"(g1 ... g2): q","clique":"q","children":[{"category":"sequence","label":"(g1 ... g1): s","clique":"s","children":[]}]}]},{"category":"sequence","label":"(g1 ... g3): p","clique":"p","children":[{"category":"sequence","label":"(g1 ... g2): p","clique":"p","children":[{"category":"sequence","label":"(g1 ... g1): s","clique":"s","children":[]}]},{"category":"sequence","label":"(g1 ... g2): q","clique":"q","children":[{"category":"sequence","label":"(g1 ... g1): s","clique":"s","children":[]}]}]}]}}}

=== DbCrWk/graph-norm/example/stopsign.parse.tree.json
{"label":"Autogenerated Parse Tree (g1 ... g8)","$schema":"https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/parse.tree/1.1.0.json","version":"1.1.0","vertices":["a","b","c","d","e","f","g","h"],"graphs":{"(g1 ... g8)":{"edges":[["a","a"],["a","h"],["a","b"],["a","g"],["a","c"],["a","f"],["a","d"],["a","e"],["h","h"],["h","g"],["h","a"],["h","f"],["h","b"],["h","e"],["h","c"],["h","d"],["b","b"],["b","a"],["b","c"],["b","h"],["b","d"],["b","g"],["b","e"],["b","f"],["g","g"],["g","f"],["g","h"],["g","e"],["g","a"],["g","d"],["g","b"],["g","c"],["c","c"],["c","b"],["c","d"],["c","a"],["c","e"],["c","h"],["c","f"],["c","g"],["f","f"],["f","e"],["f","g"],["f","d"],["f","h"],["f","c"],["f","a"],["f","b"],["d","d"],["d","c"],["d","e"],["d","b"],["d","f"],["d","a"],["d","g"],["d","h"],["e","e"],["e","d"],["e","f"],["e","c"],["e","g"],["e","b"],["e","h"],["e","a"]]},"(g1 ... g6)":{"edges":[["a","a"],["a","h"],["a","b"],["a","g"],["a","c"],["a","f"],["a","d"],["h","h"],["h","g"],["h","a"],["h","f"],["h","b"],["h","e"],["h","c"],["b","b"],["b","a"],["b","c"],["b","h"],["b","d"],["b","g"],["b","e"],["g","g"],["g","f"],["g","h"],["g","e"],["g","a"],["g","d"],["g","b"],["c","c"],["c","b"],["c","d"],["c","a"],["c","e"],["c","h"],["c","f"],["f","f"],["f","e"],["f","g"],["f","d"],["f","h"],["f","c"],["f","a"],["d","d"],["d","c"],["d","e"],["d","b"],["d","f"],["d","a"],["d","g"],["e","e"],["e","d"],["e","f"],["e","c"],["e","g"],["e","b"],["e","h"]]},"(g1 ... g5)":{"edges":[["a","a"],["a","b"],["a","h"],["a","c"],["a","g"],["a","d"],["b","b"],["b","c"],["b","a"],["b","d"],["b","h"],["b","e"],["h","h"],["h","a"],["h","g"],["h","b"],["h","f"],["h","c"],["c","c"],["c","d"],["c","b"],["c","e"],["c","a"],["c","f"],["g","g"],["g","h"],["g","f"],["g","a"],["g","e"],["g","b"],["d","d"],["d","e"],["d","c"],["d","f"],["d","b"],["d","g"],["f","f"],["f","g"],["f","e"],["f","h"],["f","d"],["f","a"],["e","e"],["e","f"],["e","d"],["e","g"],["e","c"],["e","h"]]},"(g1 ... g4)":{"edges":[["a","a"],["a","h"],["a","b"],["a","g"],["a","c"],["h","h"],["h","g"],["h","a"],["h","f"],["h","b"],["b","b"],["b","a"],["b","c"],["b","h"],["b","d"],["g","g"],["g","f"],["g","h"],["g","e"],["g","a"],["c","c"],["c","b"],["c","d"],["c","a"],["c","e"],["d","d"],["d","c"],["d","e"],["d","b"],["d","f"],["f","f"],["f","e"],["f","g"],["f","d"],["f","h"],["e","e"],["e","d"],["e","f"],["e","c"],["e","g"]]},"(g1 ... g3)":{"edges":[["a","a"],["a","b"],["a","h"],["a","c"],["b","b"],["b","c"],["b","a"],["b","d"],["h","h"],["h","a"],["h","g"],["h","b"],["c","c"],["c","d"],["c","b"],["c","e"],["g","g"],["g","h"],["g","f"],["g","a"],["d","d"],["d","e"],["d","c"],["d","f"],["e","e"],["e","f"],["e","d"],["e","g"],["f","f"],["f","g"],["f","e"],["f","h"]]},"(g1 ... g2)":{"edges":[["a","a"],["a","h"],["a","b"],["h","h"],["h","g"],["h","a"],["b","b"],["b","a"],["b","c"],["c","c"],["c","b"],["c","d"],["d","d"],["d","c"],["d","e"],["e","e"],["e","d"],["e","f"],["f","f"],["f","e"],["f","g"],["g","g"],["g","f"],["g","h"]]},"(g1 ... g1)":{"edges":[["a","a"],["a","b"],["b","b"],["b","c"],["c","c"],["c","d"],["d","d"],["d","e"],["e","e"],["e","f"],["f","f"],["f","g"],["g","g"],["g","h"],["h","h"],["h","a"]]},"g1":{"edges":[["a","a"],["a","b"],["b","b"],["b","c"],["c","c"],["c","d"],["d","d"],["d","e"],["e","e"],["e","f"],["f","f"],["f","g"],["g","g"],["g","h"],["h","h"],["h","a"]]},"g2":{"edges":[["a","a"],["a","h"],["b","b"],["b","a"],["c","c"],["c","b"],["d","d"],["d","c"],["e","e"],["e","d"],["f","f"],["f","e"],["g","g"],["g","f"],["h","h"],["h","g"]]},"g3":{"edges":[["a","a"],["a","b"],["b","b"],["b","c"],["c","c"],["c","d"],["d","d"],["d","e"],["e","e"],["e","f"],["f","f"],["f","g"],["g","g"],["g","h"],["h","h"],["h","a"]]},"g4":{"edges":[["a","a"],["a","h"],["b","b"],["b","a"],["c","c"],["c","b"],["d","d"],["d","c"],["e","e"],["e","d"],["f","f"],["f","e"],["g","g"],["g","f"],["h","h"],["h","g"]]},"g5":{"edges":[["a","a"],["a","b"],["b","b"],["b","c"],["c","c"],["c","d"],["d","d"],["d","e"],["e","e"],["e","f"],["f","f"],["f","g"],["g","g"],["g","h"],["h","h"],["h","a"]]},"g6":{"edges":[["a","a"],["a","h"],["b","b"],["b","a"],["c","c"],["c","b"],["d","d"],["d","c"],["e","e"],["e","d"],["f","f"],["f","e"],["g","g"],["g","f"],["h","h"],["h","g"]]},"g7":{"edges":[["a","a"],["a","b"],["b","b"],["b","c"],["c","c"],["c","d"],["d","d"],["d","e"],["e","e"],["e","f"],["f","f"],["f","g"],["g","g"],["g","h"],["h","h"],["h","a"]]},"(g8 ... g8)":{"edges":[["a","a"],["a","h"],["b","b"],["b","a"],["c","c"],["c","b"],["d","d"],["d","c"],["e","e"],["e","d"],["f","f"],["f","e"],["g","g"],["g","f"],["h","h"],["h","g"]]},"g8":{"edges":[["a","a"],["a","h"],["b","b"],["b","a"],["c","c"],["c","b"],["d","d"],["d","c"],["e","e"],["e","d"],["f","f"],["f","e"],["g","g"],["g","f"],["h","h"],["h","g"]]}},"sequence":["g1","g2","g3","g4","g5","g6","g7","g8"],"temporal":{"label":"Autogenerated ((g1 ... g8))","version":"1.0.0","root":{"category":"sequence","label":"(g1 ... g8)","isTransitive":true,"children":[{"category":"sequence","label":"(g1 ... g6)","isTransitive":false,"children":[{"category":"sequence","label":"(g1 ... g5)","isTransitive":false,"children":[{"category":"sequence","label":"(g1 ... g4)","isTransitive":false,"children":[{"category":"sequence","label":"(g1 ... g3)","isTransitive":false,"children":[{"category":"sequence","label":"(g1 ... g2)","isTransitive":false,"children":[{"category":"sequence","label":"(g1 ... g1)","isTransitive":false,"children":[{"category":"graph","label":"g1","isTransitive":false}]},{"category":"graph","label":"g2","isTransitive":false}]},{"category":"graph","label":"g3","isTransitive":false}]},{"category":"graph","label":"g4","isTransitive":false}]},{"category":"graph","label":"g5","isTransitive":false}]},{"category":"graph","label":"g6","isTransitive":false}]},{"category":"graph","label":"g7","isTransitive":false},{"category":"sequence","label":"(g8 ... g8)","isTransitive":false,"children":[{"category":"graph","label":"g8","isTransitive":false}]}]}},"topological":{"label":"Autogenerated (root)","version":"1.0.0","root":{"category":"root","label":"root","children":[{"category":"sequence","label":"(g1 ... g8): b","clique":"b","children":[{"category":"sequence","label":"(g1 ... g6): b","clique":"b","children":[{"category":"sequence","label":"(g1 ... g5): h","clique":"h","children":[{"category":"sequence","label":"(g1 ... g4): b","clique":"b","children":[{"category":"sequence","label":"(g1 ... g3): h","clique":"h","children":[{"category":"sequence","label":"(g1 ... g2): b","clique":"b","children":[{"category":"sequence","label":"(g1 ... g1): h","clique":"h","children":[]}]}]}]}]}]},{"category":"sequence","label":"(g8 ... g8): b","clique":"b","children":[]}]}]}}}

=== DbCrWk/graph-norm/example/waveyield.parse.tree.json
{"label":"Autogenerated Parse Tree (g1 ... g8)","$schema":"https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/parse.tree/1.1.0.json","version":"1.1.0","vertices":["a","b","c","d","e","f","g","h"],"graphs":{"(g1 ... g8)":{"edges":[["a","a"],["a","d"],["a","b"],["a","c"],["d","d"],["d","c"],["d","a"],["d","b"],["b","b"],["b","a"],["b","c"],["b","d"],["c","c"],["c","b"],["c","d"],["c","a"],["e","e"],["e","h"],["e","f"],["e","g"],["h","h"],["h","g"],["h","e"],["h","f"],["f","f"],["f","e"],["f","g"],["f","h"],["g","g"],["g","f"],["g","h"],["g","e"]]},"(g1 ... g2)":{"edges":[["a","a"],["a","d"],["a","b"],["d","d"],["d","c"],["d","a"],["b","b"],["b","a"],["b","c"],["c","c"],["c","b"],["c","d"],["e","e"],["e","h"],["e","f"],["h","h"],["h","g"],["h","e"],["f","f"],["f","e"],["f","g"],["g","g"],["g","f"],["g","h"]]},"(g1 ... g1)":{"edges":[["a","a"],["a","b"],["b","b"],["b","c"],["c","c"],["c","d"],["d","d"],["d","a"],["e","e"],["e","f"],["f","f"],["f","g"],["g","g"],["g","h"],["h","h"],["h","e"]]},"g1":{"edges":[["a","a"],["a","b"],["b","b"],["b","c"],["c","c"],["c","d"],["d","d"],["d","a"],["e","e"],["e","f"],["f","f"],["f","g"],["g","g"],["g","h"],["h","h"],["h","e"]]},"g2":{"edges":[["a","a"],["a","d"],["b","b"],["b","a"],["c","c"],["c","b"],["d","d"],["d","c"],["e","e"],["e","h"],["f","f"],["f","e"],["g","g"],["g","f"],["h","h"],["h","g"]]},"g3":{"edges":[["a","a"],["a","b"],["b","b"],["b","c"],["c","c"],["c","d"],["d","d"],["d","a"],["e","e"],["e","f"],["f","f"],["f","g"],["g","g"],["g","h"],["h","h"],["h","e"]]},"(g4 ... g5)":{"edges":[["a","a"],["a","b"],["a","d"],["b","b"],["b","c"],["b","a"],["d","d"],["d","a"],["d","c"],["c","c"],["c","d"],["c","b"],["e","e"],["e","f"],["e","h"],["f","f"],["f","g"],["f","e"],["h","h"],["h","e"],["h","g"],["g","g"],["g","h"],["g","f"]]},"(g4 ... g4)":{"edges":[["a","a"],["a","d"],["b","b"],["b","a"],["c","c"],["c","b"],["d","d"],["d","c"],["e","e"],["e","h"],["f","f"],["f","e"],["g","g"],["g","f"],["h","h"],["h","g"]]},"g4":{"edges":[["a","a"],["a","d"],["b","b"],["b","a"],["c","c"],["c","b"],["d","d"],["d","c"],["e","e"],["e","h"],["f","f"],["f","e"],["g","g"],["g","f"],["h","h"],["h","g"]]},"g5":{"edges":[["a","a"],["a","b"],["b","b"],["b","c"],["c","c"],["c","d"],["d","d"],["d","a"],["e","e"],["e","f"],["f","f"],["f","g"],["g","g"],["g","h"],["h","h"],["h","e"]]},"g6":{"edges":[["a","a"],["a","d"],["b","b"],["b","a"],["c","c"],["c","b"],["d","d"],["d","c"],["e","e"],["e","h"],["f","f"],["f","e"],["g","g"],["g","f"],["h","h"],["h","g"]]},"(g7 ... g8)":{"edges":[["a","a"],["a","d"],["a","b"],["d","d"],["d","c"],["d","a"],["b","b"],["b","a"],["b","c"],["c","c"],["c","b"],["c","d"],["e","e"],["e","h"],["e","f"],["h","h"],["h","g"],["h","e"],["f","f"],["f","e"],["f","g"],["g","g"],["g","f"],["g","h"]]},"(g7 ... g7)":{"edges":[["a","a"],["a","b"],["b","b"],["b","c"],["c","c"],["c","d"],["d","d"],["d","a"],["e","e"],["e","f"],["f","f"],["f","g"],["g","g"],["g","h"],["h","h"],["h","e"]]},"g7":{"edges":[["a","a"],["a","b"],["b","b"],["b","c"],["c","c"],["c","d"],["d","d"],["d","a"],["e","e"],["e","f"],["f","f"],["f","g"],["g","g"],["g","h"],["h","h"],["h","e"]]},"g8":{"edges":[["a","a"],["a","d"],["b","b"],["b","a"],["c","c"],["c","b"],["d","d"],["d","c"],["e","e"],["e","h"],["f","f"],["f","e"],["g","g"],["g","f"],["h","h"],["h","g"]]}},"sequence":["g1","g2","g3","g4","g5","g6","g7","g8"],"temporal":{"label":"Autogenerated ((g1 ... g8))","version":"1.0.0","root":{"category":"sequence","label":"(g1 ... g8)","isTransitive":true,"children":[{"category":"sequence","label":"(g1 ... g2)","isTransitive":false,"children":[{"category":"sequence","label":"(g1 ... g1)","isTransitive":false,"children":[{"category":"graph","label":"g1","isTransitive":false}]},{"category":"graph","label":"g2","isTransitive":false}]},{"category":"graph","label":"g3","isTransitive":false},{"category":"sequence","label":"(g4 ... g5)","isTransitive":false,"children":[{"category":"sequence","label":"(g4 ... g4)","isTransitive":false,"children":[{"category":"graph","label":"g4","isTransitive":false}]},{"category":"graph","label":"g5","isTransitive":false}]},{"category":"graph","label":"g6","isTransitive":false},{"category":"sequence","label":"(g7 ... g8)","isTransitive":false,"children":[{"category":"sequence","label":"(g7 ... g7)","isTransitive":false,"children":[{"category":"graph","label":"g7","isTransitive":false}]},{"category":"graph","label":"g8","isTransitive":false}]}]}},"topological":{"label":"Autogenerated (root)","version":"1.0.0","root":{"category":"root","label":"root","children":[{"category":"sequence","label":"(g1 ... g8): b","clique":"b","children":[{"category":"sequence","label":"(g1 ... g2): b","clique":"b","children":[{"category":"sequence","label":"(g1 ... g1): d","clique":"d","children":[]}]},{"category":"sequence","label":"(g4 ... g5): d","clique":"d","children":[{"category":"sequence","label":"(g4 ... g4): b","clique":"b","children":[]}]},{"category":"sequence","label":"(g7 ... g8): b","clique":"b","children":[{"category":"sequence","label":"(g7 ... g7): d","clique":"d","children":[]}]}]},{"category":"sequence","label":"(g1 ... g8): f","clique":"f","children":[{"category":"sequence","label":"(g1 ... g2): f","clique":"f","children":[{"category":"sequence","label":"(g1 ... g1): h","clique":"h","children":[]}]},{"category":"sequence","label":"(g4 ... g5): h","clique":"h","children":[{"category":"sequence","label":"(g4 ... g4): f","clique":"f","children":[]}]},{"category":"sequence","label":"(g7 ... g8): f","clique":"f","children":[{"category":"sequence","label":"(g7 ... g7): h","clique":"h","children":[]}]}]}]}}}
