=== DbCrWk/graph-norm/schema/parse.tree/1.1.0.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/parse.tree/1.1.0.json",
    "version": "1.1.0",
    "title": "Grano Parse Tree",
    "description": "A grano file to describe a parse tree",
    "type": "object",
    "properties": {
        "label": {
            "description": "An identifiable text identifier for this tree",
            "type": "string"
        },
        "version": {
            "description": "The version that the parse.tree should be checked against",
            "type": "string",
            "enum": [
                "1.1.0"
            ]
        },
        "vertices": {
            "description": "A set of vertices to add to all entries of the graph sequence",
            "type": "array",
            "items": {
                "$ref": "#/definitions/vertex"
            },
            "minItems": 0,
            "uniqueItems": true
        },
        "graphs": {
            "description": "A set of graphs that can be easily referenced",
            "type": "object",
            "patternProperties": {
                "^[A-Za-z-][A-Za-z0-9_-]*$": {
                    "$ref": "#/definitions/graph"
                }
            },
            "uniqueItems": true
        },
        "sequence": {
            "description": "The graph sequence",
            "type": "array",
            "items": {
                "oneOf": [
                    {
                        "$ref": "#/definitions/graph_with_label"
                    },
                    {
                        "$ref": "#/definitions/graph_label"
                    }
                ]
            },
            "uniqueItems": false
        },
        "temporal": {
            "$ref": "https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/temporal.tree/1.0.0.json"
        },
        "topological": {
            "$ref": "https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/topological.tree/1.0.0.json"
        },
        "$schema": {
            "type": "string",
            "enum": [
                "https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/parse.tree/1.1.0.json"
            ]
        }
    },
    "definitions": {
        "vertex": {
            "description": "A single vertex",
            "type": [
                "number",
                "string"
            ]
        },
        "edge": {
            "description": "A single edge",
            "type": "array",
            "items": [
                {
                    "$ref": "#/definitions/vertex"
                },
                {
                    "$ref": "#/definitions/vertex"
                }
            ],
            "minItems": 2,
            "maxItems": 2,
            "additionalItems": false
        },
        "graph_label": {
            "description": "A string identifier for a graph",
            "type": "string"
        },
        "graph": {
            "type": "object",
            "properties": {
                "label": {
                    "$ref": "#/definitions/graph_label"
                },
                "edges": {
                    "description": "A set of edges for a particular graph",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/edge"
                    },
                    "minItems": 0,
                    "uniqueItems": true
                },
                "vertices": {
                    "description": "A set of vertices for this graph",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vertex"
                    },
                    "minItems": 0,
                    "uniqueItems": true
                }
            }
        },
        "graph_with_label": {
            "$ref": "#/definitions/graph",
            "required": [
                "label"
            ]
        }
    },
    "required": [
        "label",
        "version",
        "temporal",
        "topological",
        "vertices",
        "graphs",
        "sequence"
    ],
    "additionalProperties": false
}

=== DbCrWk/graph-norm/example/t-vary.parse.tree.json
{"label":"Autogenerated Parse Tree (g1 ... g7)","$schema":"https://raw.githubusercontent.com/DbCrWk/graph-norm/development/schema/parse.tree/1.1.0.json","version":"1.1.0","vertices":["a","b","c","d","e","f"],"graphs":{"(g1 ... g7)":{"edges":[["a","a"],["a","b"],["a","c"],["a","d"],["b","b"],["b","a"],["b","c"],["b","d"],["c","c"],["c","d"],["c","a"],["c","b"],["d","d"],["d","c"],["d","a"],["d","b"],["d","f"],["d","e"],["f","f"],["f","e"],["f","d"],["f","c"],["e","e"],["e","f"],["e","d"],["e","c"],["e","a"],["e","b"]]},"(g1 ... g3)":{"edges":[["a","a"],["a","b"],["a","c"],["a","d"],["b","b"],["b","a"],["b","c"],["b","d"],["c","c"],["c","a"],["c","d"],["c","b"],["d","d"],["d","c"],["d","a"],["d","b"],["d","f"],["d","e"],["f","f"],["f","e"],["f","d"],["f","c"],["e","e"],["e","f"],["e","d"],["e","c"],["e","a"]]},"(g1 ... g2)":{"edges":[["a","a"],["a","b"],["a","c"],["b","b"],["b","a"],["b","c"],["b","d"],["c","c"],["c","a"],["c","d"],["c","b"],["d","d"],["d","c"],["d","a"],["d","f"],["d","e"],["f","f"],["f","e"],["f","d"],["e","e"],["e","d"],["e","f"],["e","c"]]},"(g1 ... g1)":{"edges":[["a","a"],["a","b"],["b","b"],["b","a"],["b","c"],["c","c"],["c","a"],["c","d"],["d","d"],["d","c"],["d","f"],["e","e"],["e","d"],["e","f"],["f","f"],["f","e"]]},"g1":{"edges":[["a","a"],["a","b"],["b","b"],["b","a"],["b","c"],["c","c"],["c","a"],["c","d"],["d","d"],["d","c"],["d","f"],["e","e"],["e","d"],["e","f"],["f","f"],["f","e"]]},"g2":{"edges":[["a","a"],["a","b"],["b","b"],["b","a"],["b","c"],["c","c"],["c","a"],["c","d"],["d","d"],["d","c"],["e","e"],["e","d"],["e","f"],["f","f"],["f","e"]]},"g3":{"edges":[["a","a"],["a","b"],["b","b"],["b","a"],["c","c"],["c","a"],["c","d"],["d","d"],["d","c"],["e","e"],["e","f"],["f","f"],["f","e"]]},"g4":{"edges":[["a","a"],["a","b"],["b","b"],["b","a"],["c","c"],["c","d"],["d","d"],["d","c"],["e","e"],["e","f"],["f","f"],["f","e"]]},"(g5 ... g7) △ tf(g1×g2×g3×g4×g5×g6×g7)":{"edges":[["a","a"],["a","b"],["a","c"],["a","d"],["b","b"],["b","a"],["b","c"],["b","d"],["c","c"],["c","d"],["d","d"],["d","c"],["f","f"],["f","e"],["f","d"],["f","c"],["e","e"],["e","f"],["e","d"],["e","c"]]},"(g5 ... g7)":{"edges":[["a","a"],["a","b"],["b","b"],["b","a"],["c","c"],["c","d"],["d","d"],["d","c"],["e","e"],["f","f"]]},"g5":{"edges":[["a","a"],["a","b"],["b","b"],["b","a"],["c","c"],["c","d"],["d","d"],["d","c"],["e","e"],["f","f"]]},"(g6 ... g7)":{"edges":[["a","a"],["a","b"],["b","b"],["b","a"],["c","c"],["d","d"],["e","e"],["f","f"]]},"g6":{"edges":[["a","a"],["a","b"],["b","b"],["b","a"],["c","c"],["d","d"],["e","e"],["f","f"]]},"(g7 ... g7)":{"edges":[["a","a"],["b","b"],["c","c"],["d","d"],["e","e"],["f","f"]]},"g7":{"edges":[["a","a"],["b","b"],["c","c"],["d","d"],["e","e"],["f","f"]]}},"sequence":["g1","g2","g3","g4","g5","g6","g7"],"temporal":{"label":"Autogenerated ((g1 ... g7))","version":"1.0.0","root":{"category":"sequence","label":"(g1 ... g7)","isTransitive":false,"children":[{"category":"sequence","label":"(g1 ... g3)","isTransitive":false,"children":[{"category":"sequence","label":"(g1 ... g2)","isTransitive":false,"children":[{"category":"sequence","label":"(g1 ... g1)","isTransitive":false,"children":[{"category":"graph","label":"g1","isTransitive":false}]},{"category":"graph","label":"g2","isTransitive":false}]},{"category":"graph","label":"g3","isTransitive":false}]},{"category":"graph","label":"g4","isTransitive":true},{"category":"special","label":"(g5 ... g7) △ tf(g1×g2×g3×g4×g5×g6×g7)","children":[{"category":"sequence","label":"(g5 ... g7)","isTransitive":true,"children":[{"category":"graph","label":"g5","isTransitive":true},{"category":"sequence","label":"(g6 ... g7)","isTransitive":true,"children":[{"category":"graph","label":"g6","isTransitive":true},{"category":"sequence","label":"(g7 ... g7)","isTransitive":true,"children":[{"category":"graph","label":"g7","isTransitive":true}]}]}]}]}]}},"topological":{"label":"Autogenerated (root)","version":"1.0.0","root":{"category":"root","label":"root","children":[{"category":"sequence","label":"(g1 ... g7): e","clique":"e","children":[{"category":"sequence","label":"(g1 ... g3): e","clique":"e","children":[{"category":"sequence","label":"(g1 ... g2): e","clique":"e","children":[{"category":"sequence","label":"(g1 ... g1): e","clique":"e","children":[]}]}]},{"category":"special","label":"(g5 ... g7) △ tf(g1×g2×g3×g4×g5×g6×g7): d","clique":"d","children":[{"category":"sequence","label":"(g5 ... g7): b","clique":"b","children":[{"category":"sequence","label":"(g6 ... g7): b","clique":"b","children":[{"category":"sequence","label":"(g7 ... g7): a","clique":"a","children":[]},{"category":"sequence","label":"(g7 ... g7): b","clique":"b","children":[]}]}]},{"category":"sequence","label":"(g5 ... g7): d","clique":"d","children":[{"category":"sequence","label":"(g6 ... g7): c","clique":"c","children":[{"category":"sequence","label":"(g7 ... g7): c","clique":"c","children":[]}]},{"category":"sequence","label":"(g6 ... g7): d","clique":"d","children":[{"category":"sequence","label":"(g7 ... g7): d","clique":"d","children":[]}]}]}]}]}]}}}
